CREATE TABLE IF NOT EXISTS users(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	fname VARCHAR(255) NOT NULL,
	lname VARCHAR(255) NOT NULL,
	password TEXT NOT NULL,
	username VARCHAR(320) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles(
	id BIGINT PRIMARY KEY GENERATED ALWAYS  AS IDENTITY,
	bio VARCHAR(512),
	avatar TEXT,
	is_verified BOOLEAN DEFAULT False,
	user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS categories(
		id BIGINT PRIMARY KEY GENERATED ALWAYS  AS IDENTITY,
		name VARCHAR(255) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	price NUMERIC(10, 2) NOT NULL,
	description TEXT,
	category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS orders(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_products(
	product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
	order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
	quantity INT NOT NULL
);

DROP TABLE order_products;




 